//! single LL
//? prepend(value)
//? append(value)
//? isEmpty()
//? print()
//? insertAt(index, value)
//? insertAfter(oldValue, newValue)
//? insertBefore(oldValue, newValue)
//? removeFrom(index)
//? removeValue(value)
//? removeMiddle()
//? get(index)
//? set(index, value)
//? reverse()
//? find(value)
//? contains(value)
//? clear()
//? toArray()
//? getSize()
//? getMiddle()
//? isPalindrome()
//? removeDuplicates()
//? sort()

